# Generated by Django 5.2.7 on 2025-11-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='insert_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
