# Generated by Django 5.2.7 on 2025-11-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_post_insert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='newapp.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='insert_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
